// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sbeqdpisoymwxcdxvtdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZXFkcGlzb3ltd3hjZHh2dGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4ODgyNzYsImV4cCI6MjA5OTQ2NDI3Nn0.UfYF-UN9TwaWr4ofrMrXoa_Hn7FW9blFmclwoRm5UTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);